name: Build and Push Docker image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: splunk-ai-agent

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check required Azure secrets
        id: secrets-check
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ACR_NAME: ${{ secrets.ACR_NAME }}
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        run: |
          missing=false
          for secret in ARM_CLIENT_ID ARM_TENANT_ID ARM_SUBSCRIPTION_ID ARM_CLIENT_SECRET ACR_NAME ACR_LOGIN_SERVER; do
            if [ -z "${!secret}" ]; then
              echo "::warning::Secret $secret is not set. Azure login and push steps will be skipped."
              missing=true
            fi
          done

          if [ "$missing" = "false" ]; then
            echo "has-secrets=true" >> "$GITHUB_OUTPUT"
          else
            echo "has-secrets=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Azure login
        uses: azure/login@v2
        if: steps.secrets-check.outputs.has-secrets == 'true'
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}

      - name: Docker login to ACR
        if: steps.secrets-check.outputs.has-secrets == 'true'
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
        run: |
          if [ -z "$ACR_NAME" ]; then
            echo "ACR_NAME secret is not set"
            exit 1
          fi
          az acr login --name "$ACR_NAME"

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Tag Docker image
        if: steps.secrets-check.outputs.has-secrets == 'true'
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        run: |
          if [ -z "$ACR_LOGIN_SERVER" ]; then
            echo "ACR_LOGIN_SERVER secret is not set"
            exit 1
          fi
          docker tag $IMAGE_NAME:latest $ACR_LOGIN_SERVER/$IMAGE_NAME:latest

      - name: Push Docker image
        if: steps.secrets-check.outputs.has-secrets == 'true'
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        run: docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest
